
The following have been reloaded with a version change:
  1) anaconda/3-4.2.0 => anaconda/3-5.1

Traceback (most recent call last):
  File "HA2.py", line 53, in <module>
    os.mkdir(atcf_data) 
FileNotFoundError: [Errno 2] No such file or directory: '/rigel/apam/users/pcd2120/clawpack/surge-examples/atlantic/nyc-ensemble/HurricaneAnalysis/data/hurricanes/atcf_data'
